import { createClient } from "npm:@supabase/supabase-js@2";
const ENDPOINTS=["https://overpass-api.de/api/interpreter","https://overpass.private.coffee/api/interpreter"];
const BOXES=[[44.0,15.5,45.4,17.7],[44.0,17.7,45.4,19.8],[42.4,15.5,44.0,17.7],[42.4,17.7,44.0,19.8]];
const aliases:Array<[string,string[]]>=[["addiko",["addiko"]],["asa_banka",["asa banka","asa"]],["bbi",["bbi","bosna bank international"]],["intesa",["intesa","intesa sanpaolo"]],["kib",["kib","komercijalno investiciona"]],["nlb",["nlb"]],["pbs",["privredna banka sarajevo","pbs"]],["procredit",["procredit","pro credit"]],["raiffeisen",["raiffeisen"]],["sparkasse",["sparkasse"]],["unicredit",["unicredit","uni credit"]],["union",["union banka","union bank"]],["ziraat",["ziraat"]],["atos",["atos"]],["bpsbl",["postanska stedionica","poštanska štedionica","bps"]],["mf",["mf banka","mf bank"]],["nova",["nova banka","nova bank"]],["nasa",["nasa banka","naša banka"]]];
function norm(v:unknown){return String(v??"").trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function bankKey(t:Record<string,unknown>){const h=norm([t.operator,t.brand,t.name,t.network].join(" "));for(const[k,vs]of aliases)if(vs.some(v=>h.includes(norm(v))))return k;return null;}
function admin(){const u=Deno.env.get("SUPABASE_URL")??"";const b=Deno.env.get("SUPABASE_SECRET_KEYS");let k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";if(b){try{k=JSON.parse(b).default??k;}catch(_){}}if(!u||!k)throw new Error("Admin credentials unavailable");return createClient(u,k,{auth:{persistSession:false}});}
async function fetchBox(box:number[]){const q=`[out:json][timeout:45];nwr["amenity"="bank"](${box.join(",")});out center tags;`;let last:unknown;for(const endpoint of ENDPOINTS){try{const c=new AbortController();const timer=setTimeout(()=>c.abort(),55000);const r=await fetch(endpoint,{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8","User-Agent":"BalkanSmartLife-ATM-Sync/2.3"},body:new URLSearchParams({data:q}),signal:c.signal});clearTimeout(timer);if(!r.ok)throw new Error(`${endpoint}: HTTP ${r.status}`);return await r.json();}catch(e){last=e;}}throw last??new Error("No Overpass endpoint available");}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return Response.json({error:"POST required"},{status:405});try{const body=await req.json().catch(()=>({}));const sector=Number(body.sector);if(!Number.isInteger(sector)||sector<0||sector>=BOXES.length)return Response.json({error:"sector must be 0..3"},{status:400});const payload=await fetchBox(BOXES[sector]) as {elements?:Record<string,unknown>[]};const rows:Record<string,unknown>[]=[];for(const e of(Array.isArray(payload.elements)?payload.elements:[])){const type=String(e.type??"");const id=Number(e.id);const tags=(e.tags&&typeof e.tags==="object")?e.tags as Record<string,unknown>:{};let lat:number|null=null,lon:number|null=null;if(type==="node"){lat=Number(e.lat);lon=Number(e.lon);}else{const center=(e.center&&typeof e.center==="object")?e.center as Record<string,unknown>:{};lat=Number(center.lat);lon=Number(center.lon);}if(!Number.isFinite(id)||!Number.isFinite(lat)||!Number.isFinite(lon))continue;const atm=norm(tags.atm);rows.push({osm_type:type,osm_id:id,latitude:lat,longitude:lon,name:tags.name??null,operator:tags.operator??null,brand:tags.brand??null,network:tags.network??null,addr_city:tags["addr:city"]??null,addr_place:tags["addr:place"]??null,addr_street:tags["addr:street"]??null,addr_housenumber:tags["addr:housenumber"]??null,bank_key:bankKey(tags),tags,imported_at:new Date().toISOString(),atm_confirmed:["yes","true","1"].includes(atm)});}const supabase=admin();for(let i=0;i<rows.length;i+=250){const{error}=await supabase.from("bsl_osm_atm_candidates").upsert(rows.slice(i,i+250),{onConflict:"osm_type,osm_id"});if(error)throw new Error(`upsert: ${error.message}`);}const{data:matched,error:me}=await supabase.rpc("bsl_match_osm_atms");if(me)throw new Error(`match: ${me.message}`);return Response.json({ok:true,sector,bankBranches:rows.length,branchesWithAtmTag:rows.filter(r=>r.atm_confirmed===true).length,matched});}catch(e){console.error("BSL ATM BANK SECTOR SYNC ERROR",e);return Response.json({error:e instanceof Error?e.message:String(e)},{status:500});}});
